name: Build Docker with custom action
description: Replace-With-Your-Action-Description
inputs:
  path_dockerfile:
    description: "Replace-With-Your-Input-Description"
    required: false
    default: ./base_code/Dockerfile
  image_name:
    description: "Specifies the name for the generated Docker image" 
    required: true
  tag_name:
    description: "Specifies the tag to be added to the final image"
    required: false
runs:
  using: composite
  steps:
    - run: |
            if [ -z "${{ inputs.tag_name }}" ]; then
                export TAG=$(date +%s)
            else
                export TAG="${{ inputs.tag_name }}"
            fi

        echo "Update me with the necessary commands"
        docker build . --file "${{ inputs.path_dockerfile }}" --tag "${{ inputs.image_name }}:${TAG}"
      shell: bash
